project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - rapport.qmd
    - slides/

website:
  title: "Code2Text"
  description: "Générer des libellés pour la codification automatique des nomenclatures statistiques"
  navbar: false
  sidebar:
    id: "sidebar-rapport"
    search: true
    collapse-level: 2
    contents:
      - text: "🏠 Accueil"
        file: index.qmd
      - text: "📖 Rapport de stage"
        file: rapport.qmd
      - text: "📊 Version Présentation (Slides)"
        file: slides/presentation.qmd

language:
  fr:
    title-block-author-single: "Auteur"
    title-block-author-plural: "Auteurs"

format:
  html:
    theme: [rapport.scss]
    toc: true
    toc-title: "Sommaire"
    toc-depth: 3
    toc-location: left
    toc-expand: true
    number-sections: true
    number-depth: 2
    smooth-scroll: true
    fig-cap-location: bottom
    embed-resources: false